# 2.1.4 Broadcasting

### Broadcasting Mechanism for Elementwise Operations

Elementwise binary operations can be performed on tensors of different shapes using the **broadcasting mechanism**. Broadcasting follows these steps:  
1. Expand one or both tensors by copying elements along axes with length 1, so that the tensors have the same shape.  
2. Perform the elementwise operation on the resulting tensors.  

This allows operations on tensors with compatible but different shapes.

In [1]:
import torch

In [2]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

### Broadcasting Example: Mismatched Shapes

When two tensors have mismatched shapes, broadcasting can align them for elementwise operations.  
For example:  
- If `a` is a $3 \times 1$ matrix and `b` is a $1 \times 2$ matrix, their shapes do not match.  
- Broadcasting expands `a` along the columns and `b` along the rows to produce a $3 \times 2$ matrix.  
- The elementwise operation (e.g., addition) is then performed on the resulting matrices.

In [3]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [4]:
a + 5

tensor([[5],
        [6],
        [7]])

In [7]:
a + torch.tensor([5, 6])

tensor([[5, 6],
        [6, 7],
        [7, 8]])

In [8]:
bias = torch.tensor([0.0, 1.0, 2.0])
a + bias

tensor([[0., 1., 2.],
        [1., 2., 3.],
        [2., 3., 4.]])