# 2.1.2 Indexing And Slicing

Similar to Python lists, we can access tensor elements using indexing, starting from 0. Negative indexing allows access to elements from the end of the list. To access a range of elements, we use slicing (e.g., X[start:stop]), which includes the start index but excludes the stop index. If only one index or slice is specified for a tensor, it applies to axis 0. For example, [-1] selects the last row, and [1:3] selects the second and third rows.

In [1]:
import torch

In [5]:
x = torch.arange(12, dtype=torch.float32)
X = x.reshape(3, 4)

In [8]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [10]:
X[-1]

tensor([ 8.,  9., 10., 11.])

In [11]:
X[1]

tensor([4., 5., 6., 7.])

In [16]:
X[0:2, 0:2]

tensor([[0., 1.],
        [4., 5.]])

Beyond reading them, we can alsowriteelements of a matrix by specifying indices

In [20]:
X[1,2], X[1,3] = 18, 19
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 18., 19.],
        [ 8.,  9., 10., 11.]])

If we want to assign multiple elements the same value, we apply the indexing on the left-hand side of the assignment operation. For instance,[:2, :]accesses the first and secondrows, where:takes all the elements along axis 1 (column). While we discussed indexingfor matrices, this also works for vectors and for tensors of more than two dimensions.

In [21]:
X[:2, :2] = 1000
X

tensor([[1000., 1000.,    2.,    3.],
        [1000., 1000.,   18.,   19.],
        [   8.,    9.,   10.,   11.]])