# 2.1.8 Exercises

1. Run the code in this section. Change the conditional statementX == YtoX < YorX >Y, and then see what kind of tensor you can get

In [1]:
import torch

In [2]:

X = torch.tensor([[1, 2, 3], [4, 5, 6]])
Y = torch.tensor([[1, 0, 3], [4, 2, 6]])

In [4]:

# Change the condition here
result = X > Y  # or X > Y
print(result)

tensor([[False,  True, False],
        [False,  True, False]])


2. Replace the two tensors that operate by element in the broadcasting mechanism withother shapes, e.g., 3-dimensional tensors. Is the result the same as expected?

In [ ]:
A = torch.arange(6).reshape(1, 2, 3)
print(A)

tensor([[0, 1, 2],
        [3, 4, 5]])


In [15]:
B = torch.arange(24).reshape(4, 2, 3)
print(B)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23]]])


In [16]:
A + B

tensor([[[ 0,  2,  4],
         [ 6,  8, 10]],

        [[ 6,  8, 10],
         [12, 14, 16]],

        [[12, 14, 16],
         [18, 20, 22]],

        [[18, 20, 22],
         [24, 26, 28]]])