# 2.1.3 Operations

We can manipulate tensors using various mathematical operations, including elementwise operations, which apply a scalar operation to each element of a tensor. For two tensors, elementwise operations apply a binary operator to corresponding elements. Any function that maps a scalar to another scalar can be turned into an elementwise function. Unary scalar operators (e.g., f:R→R, like e^x) can also be applied elementwise to tensors.

In [ ]:
import torch

In [4]:
x =torch.randn((2, 3, 4))

In [5]:
torch.exp(x)

tensor([[[ 0.5781,  3.2976,  1.2389,  1.0644],
         [ 0.1636,  0.6408,  2.0413,  1.1664],
         [12.6321,  2.1807,  1.8174,  0.7794]],

        [[ 0.5923,  1.8932,  0.7926,  0.7635],
         [ 0.6999,  1.2638,  0.4923,  1.8886],
         [ 1.4392,  0.6122,  0.3419,  9.7691]]])

### Binary Scalar Operators and Elementwise Operations

Binary scalar operators map pairs of real numbers to a single real number, denoted as $f: \mathbb{R} \times \mathbb{R} \to \mathbb{R}$. 

- For two vectors `u` and `v` of the same shape, and a binary operator $f$, we can create a new vector `c` by applying the operator elementwise:  
  $c_i = f(u_i, v_i)$, where $c_i$, $u_i$, and $v_i$ are the $i$th elements of vectors `c`, `u`, and `v`.  
- This process is called **lifting**, where a scalar function is extended to work elementwise on vectors or tensors.  
- Standard arithmetic operators like addition (`+`), subtraction (`-`), multiplication (`*`), division (`/`), and exponentiation (`**`) are all **lifted** to elementwise operations for tensors of the same shape.

In [6]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([ 2, 2, 2, 2])
x + y, x - y, x * y, x / y, x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

### Linear Algebraic Operations and Tensor Concatenation

In addition to elementwise computations, we can perform linear algebraic operations, such as **dot products** and **matrix multiplications** (explained further in Section 2.3). 

We can also **concatenate** multiple tensors by stacking them end-to-end to form a larger tensor. To do this, we provide a list of tensors and specify the axis along which to concatenate. 

For example:
- Concatenating two matrices along **rows (axis 0)** results in an output tensor where the axis-0 length is the sum of the axis-0 lengths of the input tensors.
- Concatenating along **columns (axis 1)** results in an output tensor where the axis-1 length is the sum of the axis-1 lengths of the input tensors.

In [7]:
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))


Sometimes, we want to construct a binary tensor vialogical statements. TakeX == Yas anexample. For each positioni, j, ifX[i, j]andY[i, j]are equal, then the correspondingentry in the result takes value1, otherwise it takes value0.

In [8]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

Summing all the elements in the tensor yields a tensor with only one element.

In [10]:
X.sum()

tensor(66.)