# 2.5.2 Backward For Non Scalar Variables

In [3]:
import torch

In [14]:

x = torch.tensor([8.0], requires_grad=True)
y = x * 2

y.backward()
print(x.grad)

tensor([2.])


In [15]:
x.grad.zero_()

tensor([0.])

In [16]:
y = x * x
y.backward(gradient = torch.ones(len(y)))

In [17]:
x.grad

tensor([16.])

look at this page again later