# 2.5.3 Detaching Computation

In [25]:
# Let's set up our variables
import torch

x = torch.arange(4.0, requires_grad=True)
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [26]:
# Create y = x * x
y = x * x
y

tensor([0., 1., 4., 9.], grad_fn=<MulBackward0>)

In [27]:
# Create u by detaching y from the computation graph
u = y.detach()
u

tensor([0., 1., 4., 9.])

In [28]:
# Create z = x * u and compute gradients
z = u * x
z.sum().backward()
x.grad == u

tensor([True, True, True, True])

Note that while this procedure detaches y's ancestors from the graph leading to z, the computational graph leading to y persists and thus we can calculate the gradient of y with respect to x.

In [29]:
# We can still compute gradients for y with respect to x
x.grad.zero_()  # Clear previous gradients
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

In [30]:
x = torch.arange(4.0)
print(x)

tensor([0., 1., 2., 3.])


In [31]:
x = torch.arange(4.0)
x.requires_grad_(True)
print(x.grad)

None


In [32]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [33]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [34]:
x.grad.zero_()

tensor([0., 0., 0., 0.])

In [35]:
y = x * x

In [36]:
u = y.detach()
z = u * x

In [37]:
z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [38]:
x.grad.zero_()

tensor([0., 0., 0., 0.])

In [39]:
y.sum().backward()
print(x.grad == 2 * x)

tensor([True, True, True, True])


ltpl