# 2.3.10 Matrix Matrix Multiplication

### Matrix-Matrix Multiplication

Matrix-matrix multiplication is a natural extension of dot products and matrix-vector products.  

#### Definition
- Given two matrices $\mathbf{A} \in \mathbb{R}^{n \times k}$ and $\mathbf{B} \in \mathbb{R}^{k \times m}$:  
  $\mathbf{A} = \begin{bmatrix} 
  a_{11} & a_{12} & \cdots & a_{1k} \\ 
  a_{21} & a_{22} & \cdots & a_{2k} \\ 
  \vdots & \vdots & \ddots & \vdots \\ 
  a_{n1} & a_{n2} & \cdots & a_{nk} 
  \end{bmatrix}, \quad 
  \mathbf{B} = \begin{bmatrix} 
  b_{11} & b_{12} & \cdots & b_{1m} \\ 
  b_{21} & b_{22} & \cdots & b_{2m} \\ 
  \vdots & \vdots & \ddots & \vdots \\ 
  b_{k1} & b_{k2} & \cdots & b_{km} 
  \end{bmatrix}.$ 

- The product $\mathbf{C} = \mathbf{A}\mathbf{B} \in \mathbb{R}^{n \times m}$ is computed by taking the **dot product** of each row of $\mathbf{A}$ with each column of $\mathbf{B}$:  
  $c_{ij} = \mathbf{a}_i^\top \mathbf{b}_j.$

#### Key Points
- Matrix-matrix multiplication can be thought of as performing $m$ matrix-vector products or $m \times n$ dot products, and combining the results into an $n \times m$ matrix.  
- In code, matrix multiplication can be performed using `torch.mm(A, B)` or the `@` operator (e.g., `A @ B`).  
- Example:  
  ```python
  A = torch.tensor([[1, 1, 1], [2, 2, 2]])
  B = torch.ones(3, 4)
  torch.mm(A, B), A @ B
  # Output:
  # (tensor([[ 3.,  3.,  3.,  3.],
  #          [12., 12., 12., 12.]]),
  #  tensor([[ 3.,  3.,  3.,  3.],
  #          [12., 12., 12., 12.]]))

In [1]:
import torch

In [6]:
A = torch.tensor([[ 2.0, 2.0], [5.0, 4.0], [5.0, 6.0]])
B = torch.ones(2,4)

In [7]:
torch.mm(A, B), A@B

(tensor([[ 4.,  4.,  4.,  4.],
         [ 9.,  9.,  9.,  9.],
         [11., 11., 11., 11.]]),
 tensor([[ 4.,  4.,  4.,  4.],
         [ 9.,  9.,  9.,  9.],
         [11., 11., 11., 11.]]))