# 2.3.3 Matrices

### Matrices as 2nd-Order Tensors

- **Scalars** are **0th-order tensors**, **vectors** are **1st-order tensors**, and **matrices** are **2nd-order tensors**.  
- Matrices are denoted by bold capital letters (e.g., $\mathbf{X}$, $\mathbf{Y}$, $\mathbf{Z}$) and represented in code as tensors with two axes.  

#### Matrix Notation
- The expression $\mathbf{A} \in \mathbb{R}^{m \times n}$ indicates that matrix $\mathbf{A}$ contains $m \times n$ real-valued scalars, arranged in $m$ rows and $n$ columns.  
- If $m = n$, the matrix is called **square**.  
- Individual elements are referred to using subscripts for row and column indices, e.g., $a_{ij}$ is the element in the $i$th row and $j$th column.  

#### Matrix Representation in Code
- A matrix $\mathbf{A} \in \mathbb{R}^{m \times n}$ is represented as a **2nd-order tensor** with shape $(m, n)$.  
- We can convert any appropriately sized tensor into an $m \times n$ matrix using the `reshape` function.

In [2]:
import torch

In [3]:
A = torch.arange(6).reshape(3, 2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

### Transpose of a Matrix

Sometimes, we need to **flip the axes** of a matrix. When we exchange a matrix’s rows and columns, the result is called its **transpose**.  

#### Notation and Definition
- The transpose of a matrix $\mathbf{A}$ is denoted as $\mathbf{A}^\top$.  
- If $\mathbf{B} = \mathbf{A}^\top$, then $b_{ij} = a_{ji}$ for all $i$ and $j$.  
- The transpose of an $m \times n$ matrix becomes an $n \times m$ matrix:  
  $$\mathbf{A}^\top = \begin{bmatrix} 
  a_{11} & a_{21} & \cdots & a_{m1} \\ 
  a_{12} & a_{22} & \cdots & a_{m2} \\ 
  \vdots & \vdots & \ddots & \vdots \\ 
  a_{1n} & a_{2n} & \cdots & a_{mn} 
  \end{bmatrix}.$$

#### Code Implementation
- In code, we can access the transpose of any matrix using the appropriate method or attribute (e.g., `.T` in many libraries).

In [4]:
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

### Symmetric Matrices

A **symmetric matrix** is a special type of square matrix that is equal to its own transpose:  
$\mathbf{A} = \mathbf{A}^\top.$

For example, the following matrix is symmetric:  
$
\mathbf{A} = \begin{bmatrix} 
a & b & c \\ 
b & d & e \\ 
c & e & f 
\end{bmatrix}.
$
Here, $\mathbf{A} = \mathbf{A}^\top$ because $a_{ij} = a_{ji}$ for all $i$ and $j$.

In [6]:
B = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

### Matrices for Representing Datasets

Matrices are commonly used to represent datasets:  
- **Rows** correspond to individual records (e.g., data points or samples).  
- **Columns** correspond to distinct attributes (e.g., features or variables).