# 2.1.1 Getting Started

To start, we import the PyTorch lib. Note that the package name is torch 

In [1]:
import torch

A *tensor* represents a (possbily multidimensional) array of numerical values. In the onedimensional case when only one axis is needed for the data, a tensor is called a vector.
with two axes, its a matrix. With k>2 axes, we drop the specilialized names and just refer to the object as 𝑘th-order tensor.

In [3]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

Each of these values is elements of the tensor. The tensor x contains 12 elements. we can inspect the total number of elements in a tensor via its numel method

In [4]:
x.numel()

12

We can access a tensor’s shape(the length along each axis) by inspecting its shape attribute.Because we are dealing with a vector here, the shape contains just a single element and is identical to the size.

In [5]:
x.shape

torch.Size([12])

We can reshape a tensor to change its shape without altering its size or values using the reshape function. For instance, a vector x with shape (12,) can be transformed into a matrix X with shape (3, 4). The elements of the vector are rearranged row by row, maintaining their original order (e.g., x[3] == X[0, 3]).

In [6]:
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

When reshaping a tensor using reshape, specifying every shape component is unnecessary. Since the tensor's size is known, one shape component can be inferred automatically by using -1. For example, instead of x.reshape(3, 4), we can use x.reshape(-1, 4) or x.reshape(3, -1). Additionally, tensors initialized with all elements as 0s or 1s can be created using functions like zeros (e.g., zeros((2, 3, 4))).

In [7]:
X = x.reshape(-1, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [8]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

We often wish to sample each element randomly (and independently) from a given prob-ability distribution. For example, the parameters of neural networks are often initializedrandomly. The following snippet creates a tensor with elements drawn from a standardGaussian (normal) distribution with mean 0 and standard deviation 1.

In [12]:
torch.rand((2, 3, 4))

tensor([[[0.2634, 0.5771, 0.6990, 0.5434],
         [0.6460, 0.3111, 0.0156, 0.5119],
         [0.7056, 0.4714, 0.8856, 0.0515]],

        [[0.9489, 0.4019, 0.1909, 0.1817],
         [0.6776, 0.8510, 0.9849, 0.9095],
         [0.8791, 0.3609, 0.0749, 0.6149]]])

Finally, we can construct tensors by supplying the exact values for each element by sup-plying (possibly nested) Python list(s) containing numerical literals. Here, we construct amatrix with a list of lists, where the outermost list corresponds to axis 0, and the inner listcorresponds to axis 1.


In [13]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])