# 2.3.5 Basic Properties Of Tensor Arithmetic

### Properties of Scalars, Vectors, Matrices, and Tensors

Scalars, vectors, matrices, and higher-order tensors share useful properties.  
- **Elementwise operations**: These operations produce outputs with the same shape as their operands.

In [2]:
import torch

In [4]:
A = torch.arange(6, dtype=torch.float32).reshape((2, 3))
B = A.clone()
A, A+B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [6]:
A + B == (2 * A)

tensor([[True, True, True],
        [True, True, True]])

### Hadamard Product of Matrices

The **elementwise product** of two matrices is called their **Hadamard product** (denoted as $\odot$).  

For two matrices $\mathbf{A}, \mathbf{B} \in \mathbb{R}^{m \times n}$, the Hadamard product $\mathbf{A} \odot \mathbf{B}$ is computed as:  
$$
\mathbf{A} \odot \mathbf{B} = \begin{bmatrix} 
a_{11}b_{11} & a_{12}b_{12} & \cdots & a_{1n}b_{1n} \\ 
a_{21}b_{21} & a_{22}b_{22} & \cdots & a_{2n}b_{2n} \\ 
\vdots & \vdots & \ddots & \vdots \\ 
a_{m1}b_{m1} & a_{m2}b_{m2} & \cdots & a_{mn}b_{mn} 
\end{bmatrix}.
$$

In [7]:
A * B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [11]:
A * B == A.pow(2)

tensor([[True, True, True],
        [True, True, True]])

### Scalar and Tensor Operations

Adding or multiplying a **scalar** and a **tensor** produces a result with the same shape as the original tensor.  
- Each element of the tensor is added to (or multiplied by) the scalar.

In [12]:
a = 2
X = torch.arange(24).reshape((2, 3, 4))
a * X, (a * X).shape

(tensor([[[ 0,  2,  4,  6],
          [ 8, 10, 12, 14],
          [16, 18, 20, 22]],
 
         [[24, 26, 28, 30],
          [32, 34, 36, 38],
          [40, 42, 44, 46]]]),
 torch.Size([2, 3, 4]))